import React from "react";
import Head from "next/head";
import Work from "../../components/Work/Work";
const work = () => {
  return (
    <>
      <Head>
        <title>Teerapat Work</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <div className=" relative w-full">
        <Work />
      </div>
    </>
  );
};

export default work;
